-- ponytail: no migration tool, add one (Flyway) when the schema has to change on a database that already has data.
CREATE TABLE IF NOT EXISTS cars (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          text NOT NULL CHECK (type IN ('BEV', 'ICE', 'FCEV')),
    brand         text NOT NULL,
    license_plate text NOT NULL UNIQUE,
    mileage       integer NOT NULL CHECK (mileage >= 0),
    status        text NOT NULL,
    rate          numeric(8, 2) NOT NULL CHECK (rate >= 0),
    latitude      double precision NOT NULL,
    longitude     double precision NOT NULL,
    doors         integer NOT NULL,
    body_style    text NOT NULL,
    model_year    integer NOT NULL,
    power         integer NOT NULL,
    transmission  text NOT NULL,
    color         text NOT NULL,
    -- Only for ICE cars.
    fuel_type     text,
    -- Tank or battery size and consumption per 100 km: kWh for BEV, litres for ICE, kg for FCEV.
    capacity      double precision NOT NULL,
    consumption   double precision NOT NULL,
    CHECK ((type = 'ICE') = (fuel_type IS NOT NULL))
);

-- Seed data, only when the table is empty.
INSERT INTO cars (type, brand, license_plate, mileage, status, rate, latitude, longitude, doors, body_style,
                  model_year, power, transmission, color, fuel_type, capacity, consumption)
SELECT * FROM (VALUES
    ('ICE',  'Peugeot',          '85-GHB-2',  217349, 'Available',   25.00, 10.0,     29.294,  5, 'Hatchback',    2008,  95, 'Manual',    'Black',  'Petrol', 50.0, 6.10),
    ('BEV',  'Tesla Model 3',    'K-123-BV',   48210, 'Available',   55.00, 52.3676,  4.9041,  4, 'Sedan',        2021, 208, 'Automatic', 'White',  NULL,     60.0, 14.5),
    ('FCEV', 'Toyota Mirai',     'XT-482-H',   32500, 'Available',   70.00, 51.9244,  4.4777,  4, 'Sedan',        2022, 134, 'Automatic', 'Blue',   NULL,      5.6, 0.76),
    ('ICE',  'Volkswagen Golf',  'H-482-LK',   84200, 'Available',   35.00, 52.0907,  5.1214,  5, 'Hatchback',    2019,  85, 'Manual',    'Grey',   'Petrol', 50.0, 5.4),
    ('ICE',  'Volvo V60',        'KL-283-D',  126500, 'Rented',      48.00, 51.4416,  5.4697,  5, 'Stationwagon', 2018, 140, 'Automatic', 'Silver', 'Diesel', 60.0, 4.9),
    ('ICE',  'Renault Clio',     '7-TNP-62',   61000, 'Available',   28.00, 51.5719,  4.7683,  5, 'Hatchback',    2020,  67, 'Manual',    'Red',    'Petrol', 42.0, 5.2),
    ('ICE',  'Ford Focus',       'ZV-117-P',  143000, 'Maintenance', 30.00, 53.2194,  6.5665,  5, 'Hatchback',    2016,  92, 'Manual',    'Blue',   'LPG',    52.0, 7.4),
    ('ICE',  'Mazda MX-5',       'R-905-ZB',   38900, 'Available',   60.00, 52.1601,  4.4970,  2, 'Cabrio',       2021, 135, 'Manual',    'Red',    'Petrol', 45.0, 6.8),
    ('BEV',  'Nissan Leaf',      'N-641-GH',   72300, 'Available',   38.00, 52.0116,  4.3571,  5, 'Hatchback',    2020, 110, 'Automatic', 'White',  NULL,     40.0, 16.0),
    ('BEV',  'Renault Zoe',      'G-208-RT',   55100, 'Rented',      32.00, 52.2215,  6.8937,  5, 'Hatchback',    2021, 100, 'Automatic', 'Blue',   NULL,     52.0, 17.2),
    ('BEV',  'Hyundai Kona',     'XB-370-F',   29800, 'Available',   52.00, 51.8126,  5.8372,  5, 'SUV',          2023, 150, 'Automatic', 'Grey',   NULL,     64.0, 14.7),
    ('FCEV', 'Hyundai Nexo',     'TS-556-K',   21400, 'Available',   75.00, 52.0705,  4.3007,  5, 'SUV',          2022, 120, 'Automatic', 'Silver', NULL,      6.3, 0.95),
    ('FCEV', 'Toyota Mirai',     'VP-912-N',   18700, 'Available',   72.00, 52.3874,  4.6462,  4, 'Sedan',        2023, 134, 'Automatic', 'Black',  NULL,      5.6, 0.76)
) AS seed
WHERE NOT EXISTS (SELECT 1 FROM cars);
